#syntax=docker/dockerfile:1.3

FROM gradle:7.4.2-jdk17 as builder
LABEL stage=builder_access_transit_main
WORKDIR /app
RUN echo 
COPY finer-grained-abac/access_control/graph-based-policy-machine/ /app/

RUN apt update && apt -y install  curl
RUN gradle build -x test


FROM eclipse-temurin:17-jre-alpine
LABEL description="Fine Grained Access Control"
RUN mkdir /app
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar /app/app.jar
RUN apk add curl
RUN curl -sfL $(curl -s https://api.github.com/repos/powerman/dockerize/releases/latest | grep -i /dockerize-$(uname -s)-$(uname -m)\" | cut -d\" -f4) | install /dev/stdin /usr/local/bin/dockerize

COPY start.sh start.sh

COPY start_test.sh start_test.sh

#docker build -f Dockerfile_rancher -t devdocker.wifa.uni-leipzig.de:5000/transit/fine-grained:latest .
#docker push  devdocker.wifa.uni-leipzig.de:5000/transit/fine-grained:latest


   
