version: "3"
services:
  neo4jtest:
    image: neo4j:latest
    volumes_from:
      - access-control-db-volume-neo
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/12345678
    restart: unless-stopped
  access-control-db-volume-neo:
    image: rawmind/alpine-volume:0.0.2-4
    environment:
      SERVICE_GID: '7474'
      SERVICE_UID: '7474'
      SERVICE_VOLUME: /data
    network_mode: none
    volumes:
      - access-control-db-store-neo:/data
    #  - ./config:/var/lib/neo4j/import
    labels:
      io.rancher.container.start_once: 'true'
      project: transit
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

volumes:
  access-control-db-store-neo:
    driver: local

#docker-compose -f neo4j-docker.yml up -d    
