version: "2"
services:
  db:
    image: devdocker.wifa.uni-leipzig.de:5000/transit/geoservice-db:latest
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      #POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - local_pgdata:/var/lib/postgresql/data




volumes:
  local_pgdata:
    driver: local


#docker-compose --env-file config/.env.prod up -d --build

