version: '2'
services:
  redis-cache:
    image: redis:7.2.0
    restart: unless-stopped 
    labels:
      io.rancher.scheduler.affinity:host_label: role=worker
      project: transit
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
 #   ports:
 #     - 6379:6379


#docker-compose up -d  
#rancher up -s stage-transit-backend-cache -f docker-compose.yml -u -c -d 

