version: '2'

services:
  spring-app:
    image: devdocker.wifa.uni-leipzig.de:5000/transit/fine-grained:latest
    restart: unless-stopped 
    command: "/bin/sh start.sh"
    environment:
      SPRING_NEO4J_URI: bolt://access-control-fine-grained-neo:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: 12345678
      SERVER_SERVLET_CONTEXT_PATH: /api/v1
      SERVER_PORT : 8085
    depends_on:
      - access-control-fine-grained-neo
    labels:
      io.rancher.scheduler.affinity:host_label: role=worker
      project: TO_BE_DEFINED
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    external_links:
      - transit-fine-grained-test/access-control-fine-grained-neo:access-control-fine-grained-neo
     

#docker-compose -f docker-compose.yml up -d  
#rancher up -s transit-fine-grained-api -f docker-compose.yml -u -c -d 

