version: "2"
services:
  access-control-fine-grained-neo:
    image: neo4j:5.8.0
    volumes_from:
      - access-control-fine-grained-volume-neo
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      #Initial Password, have to change
      - NEO4J_AUTH=neo4j/12345678
    restart: unless-stopped
    labels:
      io.rancher.scheduler.affinity:host_label: role=worker
      project: TO_BE_DEFINED
      io.rancher.sidekicks: access-control-fine-grained-volume-neo
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

  access-control-fine-grained-volume-neo:
    image: rawmind/alpine-volume:0.0.2-4
    environment:
      SERVICE_GID: '7474'
      SERVICE_UID: '7474'
      SERVICE_VOLUME: /data
    network_mode: none
    volumes:
      - access-control-fine-grained-store-neo:/data
    labels:
      io.rancher.container.start_once: 'true'
      project: TO_BE_DEFINED
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always   

volumes:
  access-control-fine-grained-store-neo:
    driver: local

#docker-compose -f docker-compose-db-neo.yml up -d
#rancher up -s transit-fine-grained-test -f docker-compose-db-neo.yml -u -c -d 